data <- read.csv("data/household_power_consumption.txt", header=TRUE, sep=";")
feb_data <- subset(data,data$Date=='1/2/2007' | data$Date=='2/2/2007')
remove(data)
dateandtime <- paste(as.Date(feb_data$Date,format="%d/%m/%Y"), feb_data$Time)
dateandtime <- strptime(dateandtime,"%Y-%m-%d %H:%M:%S")
plot(dateandtime, as.numeric(as.character(feb_data$Global_active_power)), type="l", ylab="Global Active Power(kilowatts)", xlab="" )
dev.copy(png,"plot2.png", width=480, height=480)
dev.off()
